### ISSUE TITLE
Lazyloading issue on static Map

### ISSUE THREAD

**Issue by Lith** [scaleflex/ng-cloudimage-responsive#14]
Hello,

When we configure `lazyloading` to` true` in `CIconfig`, all image are loaded after a mouse scrolling, but on a Map (MapBox, Google, ...), the map can not be scrolled (because it's static) and images are not loaded.

Does it possible to add an option `[lazyLoading] =" false "` on `ci-img` than force to load the image without scroll waiting ?

Thanks,

**Comment by dzmitry-stramavus** [comment]
hey @Lith ,

fixed in **2.0.8**
