### ISSUE TITLE
Offset not working in ionic 5

### ISSUE THREAD

**Issue by seyhan035** [scaleflex/ng-cloudimage-responsive#18]
Hi, i am using ci-img in a component to show product images in a grid layout. But the offset parameter doesnt do anything. The image gets loaded immediately when it comes into the viewport. Is there any example code on how this should work in ionic 5? My code is pretty much like:

<ion-content>
  <ion-item>
      <product-img-comp>
           ...

**Comment by vitaly-shaposhnik** [comment]
Hi @seyhan035 !
Give us more details about your case. 
Plugin config, usage example, expected result.
