### ISSUE TITLE
Package not working in Firefox and Edge

### ISSUE THREAD

**Issue by MiselKING** [scaleflex/ng-cloudimage-responsive#2]
If you check [code sandbox](https://codesandbox.io/s/qr6zzr8rj?fontsize=14&module=%2Fsrc%2Fapp%2Fapp.module.ts) example from your README section, you will notice that an error occurs in Firefox and Edge browsers.

Firefox error: **Invalid regexp group**
Edge error: **Unexpected quantifier**

Package version: **1.0.1**

I also tested in my own app and the same error occurs...

**Comment by dzmitry-stramavus** [comment]
@MiselKING , thanks for reporting the bugs.

fixed in version **1.0.3**
**demo** and **example in code sandbox** are updated
