### ISSUE TITLE
Custom CNAME

### ISSUE THREAD

**Issue by christianjung87** [scaleflex/ng-cloudimage-responsive#21]
Hi there,
is there currently a way - i am just overlooking - to use a custom CNAME instead of {token}.cloudimg.io?

Thanks in advance for your reply!

**Comment by nganchev** [comment]
Hi,

Yes you can.
As flagged in our documentation as well - https://docs.cloudimage.io/go/cloudimage-documentation-v7/en/domains-urls 
You need to have plan supporting the CNAME and to request it from the Cloudimage support team.

Best,
