### ISSUE TITLE
No support yet for Angular 11+

### ISSUE THREAD

**Issue by Sampath-Lokuge** [scaleflex/ng-cloudimage-responsive#23]
Hi,

It gives this error. Any clue? Thanks!

> ng update @angular/core @angular/cli

>   Package "ng-cloudimage-responsive" has an incompatible peer dependency to "@angular/common" (requires "^8.1.1" (extended), would install "11.2.11").
>                   Package "ng-cloudimage-responsive" has an incompatible peer dependency to "@angular/core" (requires "^8.1.1" (extended), would install "11.2.11").
> × Migration failed: Incompatible peer dependencies found.
> Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
> You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
>   See "C:\Users\Sampath\AppData\Local\Temp\ng-mxhhvu\angular-errors.log" for further details.

We use this version now with Angular 10 and no issues there:

` "ng-cloudimage-responsive": "2.1.3",`

**Comment by vitaly-shaposhnik** [comment]
Hi @Sampath-Lokuge !
Fixed in 2.1.6 version

**Comment by Sampath-Lokuge** [comment]
Hi @vitaly-shaposhnik 
It is working now. Thanks!
