### ISSUE TITLE
Change detection might not be handled properly

### ISSUE THREAD

**Issue by jeandat** [scaleflex/ng-cloudimage-responsive#5]
I'm using the latest version of your library (1.1.0) with angular 7.

In components using the `OnPush` strategy, images are never loaded until you execute `ChangeDetectorRef.markForCheck()`. In my tests, the only thing working is the `ngAfterViewInit()` callback like demonstrated in this [demo](https://github.com/jeandat/cloudimage-angular-changedetection). Sometimes, I even have to put it in a `setTimeout()`.

IMO, this should be done by the library. Could you explain what is happening behind the scene and if that's even the right diagnostic. I'm just starting to use your library, I don't have much more to say for now.

Nota Bene: 
- the demo project has angular material has dependency but that was just a test, and the problem is reproducible without it.
- tried to import the project in stackblitz and codesandbox but it didn't worked

**Comment by jeandat** [comment]
No one managing this repo? Am I missing something obvious? Thx.

**Comment by dzmitry-stramavus** [comment]
@jeandat , hey 

I'll look into this issue during the next few days. Sorry, for long response. We are busy with launching another project.

**Comment by dzmitry-stramavus** [comment]
fixed in v1.1.1

**Comment by jeandat** [comment]
Nice. Thanks.
