### ISSUE TITLE
ci-img component doesn't react to input changes

### ISSUE THREAD

**Issue by jeandat** [scaleflex/ng-cloudimage-responsive#8]
If input parameters like `src` change over time, the component doesn't react. Indeed, only `ngOnInit` is implemented but `ngOnChanges` was forgotten.

**Comment by jeandat** [comment]
Any news on that folks? I guess this is not a big deal and it would add immediate value to the lib. Thanks.

**Comment by dzmitry-stramavus** [comment]
hey @jeandat , 

Our team was on holiday. We will do it during the week.

**Comment by vitaly-shaposhnik** [comment]
Hey @jeandat 
Fix available in 2.0.3

**Comment by jeandat** [comment]
Perfect. Thanks.
