### ISSUE TITLE
on firefox the image does not load properly when i navigate to an other page and then back

### ISSUE THREAD

**Issue by kingpeti** [scaleflex/ng-cloudimage-responsive#9]
I test this on chrome it is works as it expected, but on firefox the thumb image does not refresh to the full image when i navigate to another page and then navigate to the previous page.
angular version: 8.1.2
ng-cloudimage-responsive version: 2.0.0

**Comment by dzmitry-stramavus** [comment]
hey @kingpeti,

we cannot reproduce the bug. Try to update to latest version and check again. Or provide as with some code example. Thx
